// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: pooldata.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PoolData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dex             string `protobuf:"bytes,1,opt,name=dex,proto3" json:"dex,omitempty"`
	DexId           string `protobuf:"bytes,2,opt,name=dex_id,json=dexId,proto3" json:"dex_id,omitempty"`
	Pool            string `protobuf:"bytes,3,opt,name=pool,proto3" json:"pool,omitempty"`
	PoolAddress     string `protobuf:"bytes,4,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	TokenOne        string `protobuf:"bytes,5,opt,name=token_one,json=tokenOne,proto3" json:"token_one,omitempty"`
	TokenTwo        string `protobuf:"bytes,6,opt,name=token_two,json=tokenTwo,proto3" json:"token_two,omitempty"`
	TokenOneBalance string `protobuf:"bytes,7,opt,name=token_one_balance,json=tokenOneBalance,proto3" json:"token_one_balance,omitempty"`
	TokenTwoBalance string `protobuf:"bytes,8,opt,name=token_two_balance,json=tokenTwoBalance,proto3" json:"token_two_balance,omitempty"`
	Fee             string `protobuf:"bytes,9,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (x *PoolData) Reset() {
	*x = PoolData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pooldata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolData) ProtoMessage() {}

func (x *PoolData) ProtoReflect() protoreflect.Message {
	mi := &file_pooldata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolData.ProtoReflect.Descriptor instead.
func (*PoolData) Descriptor() ([]byte, []int) {
	return file_pooldata_proto_rawDescGZIP(), []int{0}
}

func (x *PoolData) GetDex() string {
	if x != nil {
		return x.Dex
	}
	return ""
}

func (x *PoolData) GetDexId() string {
	if x != nil {
		return x.DexId
	}
	return ""
}

func (x *PoolData) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *PoolData) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *PoolData) GetTokenOne() string {
	if x != nil {
		return x.TokenOne
	}
	return ""
}

func (x *PoolData) GetTokenTwo() string {
	if x != nil {
		return x.TokenTwo
	}
	return ""
}

func (x *PoolData) GetTokenOneBalance() string {
	if x != nil {
		return x.TokenOneBalance
	}
	return ""
}

func (x *PoolData) GetTokenTwoBalance() string {
	if x != nil {
		return x.TokenTwoBalance
	}
	return ""
}

func (x *PoolData) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

var File_pooldata_proto protoreflect.FileDescriptor

var file_pooldata_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x6f, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x22, 0x8e, 0x02, 0x0a, 0x08, 0x50, 0x6f, 0x6f, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x65, 0x78, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x65, 0x78, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6f, 0x6c,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f, 0x6f, 0x6c, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6f, 0x6e, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4f, 0x6e, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x77, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x77, 0x6f, 0x12, 0x2a, 0x0a,
	0x11, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6f, 0x6e, 0x65, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4f,
	0x6e, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x74, 0x77, 0x6f, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x77, 0x6f, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pooldata_proto_rawDescOnce sync.Once
	file_pooldata_proto_rawDescData = file_pooldata_proto_rawDesc
)

func file_pooldata_proto_rawDescGZIP() []byte {
	file_pooldata_proto_rawDescOnce.Do(func() {
		file_pooldata_proto_rawDescData = protoimpl.X.CompressGZIP(file_pooldata_proto_rawDescData)
	})
	return file_pooldata_proto_rawDescData
}

var file_pooldata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pooldata_proto_goTypes = []interface{}{
	(*PoolData)(nil), // 0: pool.PoolData
}
var file_pooldata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pooldata_proto_init() }
func file_pooldata_proto_init() {
	if File_pooldata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pooldata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pooldata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pooldata_proto_goTypes,
		DependencyIndexes: file_pooldata_proto_depIdxs,
		MessageInfos:      file_pooldata_proto_msgTypes,
	}.Build()
	File_pooldata_proto = out.File
	file_pooldata_proto_rawDesc = nil
	file_pooldata_proto_goTypes = nil
	file_pooldata_proto_depIdxs = nil
}
